// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package nanabushv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// TranslationServiceClient is the client API for TranslationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TranslationServiceClient interface {
	// RegisterClient registers a new client with the server.
	// This should be called immediately after establishing a connection.
	// Returns a client_id that should be used for subsequent heartbeats.
	RegisterClient(ctx context.Context, in *RegisterClientRequest, opts ...grpc.CallOption) (*RegisterClientResponse, error)
	// Heartbeat sends a keepalive and re-authentication signal from the client.
	// Should be called periodically (recommended: every 30-60 seconds).
	// If the socket is torn down, the client should re-register.
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// CheckTitle performs a lightweight pre-flight check with title only.
	// This validates that Nanabush is ready and can handle the request.
	CheckTitle(ctx context.Context, in *TitleCheckRequest, opts ...grpc.CallOption) (*TitleCheckResponse, error)
	// Translate performs full document translation.
	// This is the main translation endpoint that processes complete documents.
	Translate(ctx context.Context, in *TranslateRequest, opts ...grpc.CallOption) (*TranslateResponse, error)
	// TranslateStream supports streaming for large documents.
	// Client sends chunks, server responds with translated chunks.
	TranslateStream(ctx context.Context, opts ...grpc.CallOption) (TranslationService_TranslateStreamClient, error)
}

type translationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTranslationServiceClient(cc grpc.ClientConnInterface) TranslationServiceClient {
	return &translationServiceClient{cc}
}

func (c *translationServiceClient) RegisterClient(ctx context.Context, in *RegisterClientRequest, opts ...grpc.CallOption) (*RegisterClientResponse, error) {
	out := new(RegisterClientResponse)
	err := c.cc.Invoke(ctx, "/nanabush.v1.TranslationService/RegisterClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *translationServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, "/nanabush.v1.TranslationService/Heartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *translationServiceClient) CheckTitle(ctx context.Context, in *TitleCheckRequest, opts ...grpc.CallOption) (*TitleCheckResponse, error) {
	out := new(TitleCheckResponse)
	err := c.cc.Invoke(ctx, "/nanabush.v1.TranslationService/CheckTitle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *translationServiceClient) Translate(ctx context.Context, in *TranslateRequest, opts ...grpc.CallOption) (*TranslateResponse, error) {
	out := new(TranslateResponse)
	err := c.cc.Invoke(ctx, "/nanabush.v1.TranslationService/Translate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *translationServiceClient) TranslateStream(ctx context.Context, opts ...grpc.CallOption) (TranslationService_TranslateStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TranslationService_serviceDesc.Streams[0], "/nanabush.v1.TranslationService/TranslateStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &translationServiceTranslateStreamClient{stream}
	return x, nil
}

type TranslationService_TranslateStreamClient interface {
	Send(*TranslateChunk) error
	Recv() (*TranslateChunk, error)
	grpc.ClientStream
}

type translationServiceTranslateStreamClient struct {
	grpc.ClientStream
}

func (x *translationServiceTranslateStreamClient) Send(m *TranslateChunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *translationServiceTranslateStreamClient) Recv() (*TranslateChunk, error) {
	m := new(TranslateChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TranslationServiceServer is the server API for TranslationService service.
// All implementations must embed UnimplementedTranslationServiceServer
// for forward compatibility
type TranslationServiceServer interface {
	// RegisterClient registers a new client with the server.
	// This should be called immediately after establishing a connection.
	// Returns a client_id that should be used for subsequent heartbeats.
	RegisterClient(context.Context, *RegisterClientRequest) (*RegisterClientResponse, error)
	// Heartbeat sends a keepalive and re-authentication signal from the client.
	// Should be called periodically (recommended: every 30-60 seconds).
	// If the socket is torn down, the client should re-register.
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// CheckTitle performs a lightweight pre-flight check with title only.
	// This validates that Nanabush is ready and can handle the request.
	CheckTitle(context.Context, *TitleCheckRequest) (*TitleCheckResponse, error)
	// Translate performs full document translation.
	// This is the main translation endpoint that processes complete documents.
	Translate(context.Context, *TranslateRequest) (*TranslateResponse, error)
	// TranslateStream supports streaming for large documents.
	// Client sends chunks, server responds with translated chunks.
	TranslateStream(TranslationService_TranslateStreamServer) error
	mustEmbedUnimplementedTranslationServiceServer()
}

// UnimplementedTranslationServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTranslationServiceServer struct {
}

func (UnimplementedTranslationServiceServer) RegisterClient(context.Context, *RegisterClientRequest) (*RegisterClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterClient not implemented")
}
func (UnimplementedTranslationServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedTranslationServiceServer) CheckTitle(context.Context, *TitleCheckRequest) (*TitleCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckTitle not implemented")
}
func (UnimplementedTranslationServiceServer) Translate(context.Context, *TranslateRequest) (*TranslateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Translate not implemented")
}
func (UnimplementedTranslationServiceServer) TranslateStream(TranslationService_TranslateStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method TranslateStream not implemented")
}
func (UnimplementedTranslationServiceServer) mustEmbedUnimplementedTranslationServiceServer() {}

// UnsafeTranslationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TranslationServiceServer will
// result in compilation errors.
type UnsafeTranslationServiceServer interface {
	mustEmbedUnimplementedTranslationServiceServer()
}

func RegisterTranslationServiceServer(s *grpc.Server, srv TranslationServiceServer) {
	s.RegisterService(&_TranslationService_serviceDesc, srv)
}

func _TranslationService_RegisterClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranslationServiceServer).RegisterClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nanabush.v1.TranslationService/RegisterClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranslationServiceServer).RegisterClient(ctx, req.(*RegisterClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranslationService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranslationServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nanabush.v1.TranslationService/Heartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranslationServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranslationService_CheckTitle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TitleCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranslationServiceServer).CheckTitle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nanabush.v1.TranslationService/CheckTitle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranslationServiceServer).CheckTitle(ctx, req.(*TitleCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranslationService_Translate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TranslateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranslationServiceServer).Translate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nanabush.v1.TranslationService/Translate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranslationServiceServer).Translate(ctx, req.(*TranslateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranslationService_TranslateStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TranslationServiceServer).TranslateStream(&translationServiceTranslateStreamServer{stream})
}

type TranslationService_TranslateStreamServer interface {
	Send(*TranslateChunk) error
	Recv() (*TranslateChunk, error)
	grpc.ServerStream
}

type translationServiceTranslateStreamServer struct {
	grpc.ServerStream
}

func (x *translationServiceTranslateStreamServer) Send(m *TranslateChunk) error {
	return x.ServerStream.SendMsg(m)
}

func (x *translationServiceTranslateStreamServer) Recv() (*TranslateChunk, error) {
	m := new(TranslateChunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _TranslationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nanabush.v1.TranslationService",
	HandlerType: (*TranslationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterClient",
			Handler:    _TranslationService_RegisterClient_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _TranslationService_Heartbeat_Handler,
		},
		{
			MethodName: "CheckTitle",
			Handler:    _TranslationService_CheckTitle_Handler,
		},
		{
			MethodName: "Translate",
			Handler:    _TranslationService_Translate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TranslateStream",
			Handler:       _TranslationService_TranslateStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "translation-server.proto",
}
