apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: nanabush-secure
allowPrivilegedContainer: false
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
runAsUser:
  type: MustRunAsRange
seLinuxContext:
  type: MustRunAs
seccompProfiles:
  - runtime/default
  - localhost/nanabush-locked.json
users:
  - system:serviceaccount:nanabush:nanabush-controller

