apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: nanabush-grpc-l2
  namespace: openshift-operators
spec:
  ipAddressPools:
    - nanabush-grpc-pool
  # Advertise on all nodes (for SNO, this is just the one node)
  nodeSelectors:
    - matchLabels: {}

